export const DEFAULT_EVENT = {
  id: null,
  category: 'Training',
  layout: 'Left',
  title: 'Advancing Digital Cost Management in Nigerian Construction',
  subtitle: 'Hands-on training in BIM-driven quantity surveying and modern estimation workflows',
  goldWordIndex: 3,
  // Occasion fields (courtesy visit / appreciation / congratulations / condolence).
  // Ignored by the CPD layouts; see flyer/categories.js.
  host: '',        // who/where is being visited or honoured (Courtesy Visit)
  message: '',     // free-text citation / tribute / appreciation body
  dateStart: '2026-05-05',
  dateEnd: '2026-05-09',
  time: '9:00 AM daily',
  timeZone: 'WAT',
  cpdPoints: 27,
  cpdSealVariant: 'auto',
  venueType: 'Hybrid',
  venuePhysical: 'Eko Hotel & Suites',
  venueCity: 'Lagos',
  platform: 'Zoom',
  platformNote: 'Link via email',
  registrationUrl: 'niqs.org.ng/training',
  registrationExtra: 'Special discounts for lecturers & students',
  enquiries: ['08091551476', '08069514106'],
  backgroundId: 'dark-bg-1',
  accent: 'glow',
  theme: 'Dark',
  selectedSpeakerIndex: 0,
  sections: {
    cpdSeal: true,
    subtitle: true,
    themedEyebrow: true,
    speakers: true,
    presentersEyebrow: true,
    metaBlock: true,
    metaDate: true,
    metaVenue: true,
    metaPlatform: true,
    registration: true,
    contactBar: true,
  },
  schedule: 'Day 1: Introduction to Digital Workflows & BIM Fundamentals\nDay 2: Quantity Surveying with BIM & Cost Planning\nDay 3: Digital Measurement Workflows & Estimating\nDay 4: Project Management & Resource Controls\nDay 5: Practical Sessions & Case Studies',
  speakers: [
    { id: '1', name: 'QS Prof Kulomri Adogbo', credentials: '', photo: null, role: 'Faculty', topic: 'Project management & resource controls' },
    { id: '2', name: 'QS Muftau Akinpelu', credentials: '', photo: null, role: 'Faculty', topic: 'Highway infrastructure cost management' },
    { id: '3', name: 'QS Prof Ganiyu Amuda-Yusuf', credentials: '', photo: null, role: 'Faculty', topic: 'Mechanical, electrical & plumbing services' },
    { id: '4', name: 'QS Dr Aminu M. Bashir', credentials: '', photo: null, role: 'Faculty', topic: 'Digital measurement workflows & BIM' },
  ],
}
